# Site settings
title: "Kenenisa Tadesse Dame"
name: "Kenenisa Tadesse Dame"
description: "PhD Candidate in Statistical Sciences, Biostatistics and Pharmacovigilance"
baseurl: ""
url: "https://kenenitadesse.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Include custom CSS
include:
  - assets/css/main.scss
# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

# Author info (sidebar)
author:
  name: "Kenenisa Tadesse Dame"
  bio: "PhD Candidate in Statistical Sciences, University of Padova"
  location: "Padova, Italy"
  email: "kenenisatadesse@gmail.com"
  avatar: "/assets/images/profile.jpg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kenenitadesse"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kenenitadesse/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=BKsUXgcAAAAJ"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

# Build settings
markdown: kramdown
repository: "kenenitadesse/kenenitadesse.github.io"
